name: CI
on:
  pull_request:
  workflow_dispatch:
  
jobs:
  Lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint 
        uses: ./
        with:
          command: npm run lint
  Build:
    runs-on: ubuntu-22.04
    needs: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build 
        uses: ./
        with:
          command: npm run build
